import { createSlice } from "@reduxjs/toolkit";

// Define the initial state of the auth slice of the Redux store
const initialState = {
  mode: "light", // Current mode, either "light" or "dark"
  user: null, // User object, initially null until the user logs in
  token: null, // Authentication token, initially null until the user logs in
  posts: [], // Array to store posts
};

// Create a slice of the Redux store using createSlice from Redux Toolkit
export const authSlice = createSlice({
  name: "auth", // Name of the slice
  initialState, // Initial state defined above
  reducers: {
    // Reducer function to toggle between light and dark mode
    setMode: (state) => {
      state.mode = state.mode === "light" ? "dark" : "light";
    },
    // Reducer function to set user data when the user logs in
    setLogin: (state, action) => {
      state.user = action.payload.user; // Set user object
      state.token = action.payload.token; // Set authentication token
    },
    // Reducer function to clear user data and token when the user logs out
    setLogout: (state) => {
      state.user = null; // Clear user object
      state.token = null; // Clear authentication token
    },
    // Reducer function to set friends for the logged-in user
    setFriends: (state, action) => {
      if (state.user) {
        state.user.friends = action.payload.friends; // Set friends array for the user
      } else {
        console.error("user friends non-existent :("); // Log an error if the user object is null
      }
    },
    // Reducer function to set all posts in the Redux store
    setPosts: (state, action) => {
      state.posts = action.payload.posts; // Set posts array
    },
    // Reducer function to update a specific post in the Redux store
    setPost: (state, action) => {
      state.posts = state.posts.map((post) =>
        post._id === action.payload.post._id ? action.payload.post : post
      ); // Find the post in the array and update it with the new data
    },
  },
});

// Export the action creators generated by createSlice
export const { setMode, setLogin, setLogout, setFriends, setPosts, setPost } =
  authSlice.actions;

// Export the reducer function generated by createSlice
export default authSlice.reducer;
